### ISSUE TITLE
Pressing `gf` on require("./directory") should open ./directory/index.js

### ISSUE THREAD

**Issue by moll** [moll/vim-node#1]
Indeed, my split personality self. That's because we're currently depending on Vim's built-in `includeexpr` to get a chance to look up the required file and Vim thinks it can handle that relative path to an existing directory itself.

Don't yet know how to get it to pass existing directories onward to us without Vim opening them by default.

**Comment by leeren** [comment]
I know this was years ago, but I am curious how exactly you got `inlcudeexpr` to override Vim by default trying to resolve to that path (instead of opening `index.js` of that path for example)?

**Comment by moll** [comment]
@leeren, I think I did that by hooking into `gf` myself. Still seems to be the case as per https://github.com/moll/vim-node/blob/ede047791792b9530ba1ae73ed86e9671cdd96b8/autoload/node.vim#L42.

**Comment by leeren** [comment]
Thanks a lot!
