### ISSUE TITLE
Open in new window split

### ISSUE THREAD

**Issue by kentcdodds** [moll/vim-node#25]
Is there any way that vim-node could have a command to open the file in a new vertical/horizontal split? Maybe `vgf` or `hgf`? A new tab would probably be helpful as well... `tgf`

**Comment by moll** [comment]
Hey again,

https://github.com/moll/vim-node#want-c-wf-to-open-the-file-under-the-cursor-in-a-new-vertical-split
Do those work for you?

**Comment by kentcdodds** [comment]
Ah, sorry, I did a ⌘+F for `"window"` rather than `"split"` and couldn't find that. Thanks!

**Comment by moll** [comment]
Yay! :)
