### ISSUE TITLE
Jump to matched file

### ISSUE THREAD

**Issue by zhangchiqing** [moll/vim-node#33]
When I press `[I` on a keyword, I get a few matches in another window.

![screenshot 2016-01-14 12 54 32](https://cloud.githubusercontent.com/assets/811374/12337339/44fb66e4-babe-11e5-828d-d22e13b2880e.png)

How can I jump to the second match? Since each match has a number label, I assume I can jump to the second match by pressing `2`. But it doesn't work, it just simply close the window.

**Comment by moll** [comment]
Hey,

This is Vim's world renowned UI usability. See `:h [I`. :-P

In short, there's a suggestion to write a mapping to allow you to type a number for jumping:
> If you want to list matches, and then select one to jump to, you could use a mapping to do that for you.  Here is an example:
>
>  ```vim
> :map <F4> [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
> ```

**Comment by zhangchiqing** [comment]
It works! Thanks @moll :-)
