### ISSUE TITLE
Feature request: ES2015 module resolution support

### ISSUE THREAD

**Issue by trevordmiller** [moll/vim-node#35]
I was looking for a plugin that would let me use `gf` with both node `require()` and ES2015 `import` syntax; this plugin solved 3 of 4 situations:
- ✔ Relative Node modules: `const someModule = require('./someModule')`
- ✔ Resolved Node modules: `const someModule = require('someModule')`
- ✔ Relative ES2015 modules: `import someModule from './someModule'`
- 🙏 Resolved ES2015 modules: `import someModule from 'someModule'`

Because ES2015 modules are gaining greater popularity and are being considered for Node itself, it would be awesome if this plugin covered the fourth situation as well. To go along with this, this plugin could potentially be re-named to `vim-es-modules` or something...

p.s. Great plugin! Thank you for making it :)

**Comment by trevordmiller** [comment]
@moll Would love your thoughts on this if you get a chance :) Thanks again for the great plugin.

**Comment by moll** [comment]
Hey,

A short answer would be: Should probably add ES2015 modules here, too, indeed. ;)

**Comment by trevordmiller** [comment]
Would love to see it implemented, but don't feel it is valuable to keep something open for months so closing for now.

**Comment by moll** [comment]
Oh, don't worry about that. 4 months in the OSS world is nothing. We're all doing this on our free time and aside from show-stopping bugs, life takes precedence over features. :) We'll get around to this, too. ;)

**Comment by trevordmiller** [comment]
I understand, I'm an open source author as well :) But I'm going to close this since it has been another 10 months since the issue was first opened and I have moved on to another plugin and would like to tidy up my open issues.

**Comment by moll** [comment]
Ah, would you unsubscribing from this solve your orderliness desire with my keeping-it-around-until-I-get-to-it desire? :)

**Comment by agriffis** [comment]
@trevordmiller You mentioned that you moved on to another plugin. Mind saying what that is?

**Comment by trevordmiller** [comment]
@agriffis I'm not sure which plugin under the hood handles it, but since installing `vim-polyglot` and latest Vim (8+), using `gf` over `import someModule from 'someModule'` works for me :) https://github.com/trevordmiller/dotfiles/blob/master/files/.vimrc

**Comment by trevordmiller** [comment]
It's been almost two years since this issue was created. Closing this as I don't use the plugin anymore and am clearing out old issues. If you want it re-opened, please make a new issue. Thanks.

**Comment by moll** [comment]
Doesn't time fly. :) You're welcome to unsubscribe from this issue if you don't want to be notified, but I'd like to keep it open as it's a perfectly valid desire.

**Comment by trevordmiller** [comment]
@moll I use the "Issues" feature of GitHub to keep track of the issues I'm involved with which shows issues you have created, even when unsubscribed. Please stop reopening the issue. Feel free to create a new one if you'd like it.

**Comment by moll** [comment]
Hmm, I don't want to create another issue for this, but I also don't want you to be have to see it. I wonder how we could report this as a bug to GitHub...
