### ISSUE TITLE
Open path in new tab

### ISSUE THREAD

**Issue by izdesenko** [moll/vim-node#40]
Hello! Thank you for great work! Is this possible to open modules by "gf" or "[I" in new tab? That would be very handy.

**Comment by feix760** [comment]
Use ^w + gf
See: http://vi.stackexchange.com/questions/3364/open-filename-under-cursor-like-gf-but-in-a-new-tab-or-split

**Comment by moll** [comment]
Did @feix760's suggestion solve your problem, @izdesenko? Thanks for it, @feix760, by the way!

**Comment by izdesenko** [comment]
@moll actually, didn't. I inspect code all the time and it is not convinient for me to use this long shortcut. But right now i don't write node.js code so i don't need this feature.

**Comment by moll** [comment]
You're welcome to always map a shorter shortcut for that with `:nmap`. :)
I'll close this as there's nothing for us to _do_ here. We can however continue chatting. ;)
